image: ruby:2.3


stages:
  - deploy
variables:
  JEKYLL_ENV: production

before_script:
  - bundle install

test:
  stage: deploy
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
  environment:
    name: pages
    url: https://kontinu.gitlab.io/home/
