image: ruby:2.3


stages:
  - test
  - deploy
variables:
  JEKYLL_ENV: production

before_script:
  - bundle install

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master


archive:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  - tar cvfz public.tar.gz public
  artifacts:
    paths:
    - "*.tar.gz"
  only:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  - tar cvfz public.tar.gz public
  artifacts:
    paths:
    - public
    - "*.tar.gz"
  only:
  - master
  environment:
    name: pages
    url: https://www.kontinu.io/

