version: "3.3"

services:
  page:
    command: "jekyll server -P 4000 -H 0.0.0.0"
    environment:
      - JEKYLL_ENV=production
    image: starefossen/github-pages
    volumes:
      - $PWD:/usr/src/app
    ports:
      -  "${PORT:-4000}:4000"
